//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DataOnboarding.WebApplication.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Information {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Information() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DataOnboarding.WebApplication.Resource.Information", typeof(Information).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string ActionsHeader {
            get {
                return ResourceManager.GetString("ActionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Rule.
        /// </summary>
        public static string AddQCRuleText {
            get {
                return ResourceManager.GetString("AddQCRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Repository.
        /// </summary>
        public static string AddRepositoryText {
            get {
                return ResourceManager.GetString("AddRepositoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Mode.
        /// </summary>
        public static string AuthenticationModeHeader {
            get {
                return ResourceManager.GetString("AuthenticationModeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackTitle {
            get {
                return ResourceManager.GetString("BackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Practices Check.
        /// </summary>
        public static string BestPracticesCheckTitle {
            get {
                return ResourceManager.GetString("BestPracticesCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed checks to identify potential issues that might make your data less understandable to others. Some of the issues are related to {0} compatibility, and others are simply best practices for data management and organization..
        /// </summary>
        public static string BestPracticesHeader1 {
            get {
                return ResourceManager.GetString("BestPracticesHeader1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some of the potential issues listed here must be manually altered to comply with best practices..
        /// </summary>
        public static string BestPracticesHeader2 {
            get {
                return ResourceManager.GetString("BestPracticesHeader2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to modified files to fix errors. You can Ignore these errors and continue posting..
        /// </summary>
        public static string BestPracticesHeader3 {
            get {
                return ResourceManager.GetString("BestPracticesHeader3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelHeader {
            get {
                return ResourceManager.GetString("CancelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string ChangeText {
            get {
                return ResourceManager.GetString("ChangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citation.
        /// </summary>
        public static string CitationHeader {
            get {
                return ResourceManager.GetString("CitationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider headers order.
        /// </summary>
        public static string ConsiderheadersorderText {
            get {
                return ResourceManager.GetString("ConsiderheadersorderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedByHeader {
            get {
                return ResourceManager.GetString("CreatedByHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Created.
        /// </summary>
        public static string CreatedDateHeader {
            get {
                return ResourceManager.GetString("CreatedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2013 DataUp.
        /// </summary>
        public static string DataOnBoardingCopyRight {
            get {
                return ResourceManager.GetString("DataOnBoardingCopyRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete File URL.
        /// </summary>
        public static string DeleteFileURLHeader {
            get {
                return ResourceManager.GetString("DeleteFileURLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionLabel {
            get {
                return ResourceManager.GetString("DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download File URL.
        /// </summary>
        public static string DownloadFileURLHeader {
            get {
                return ResourceManager.GetString("DownloadFileURLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string DownloadTitle {
            get {
                return ResourceManager.GetString("DownloadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string DownText {
            get {
                return ResourceManager.GetString("DownText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Rule.
        /// </summary>
        public static string EditQCRuleText {
            get {
                return ResourceManager.GetString("EditQCRuleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Repository.
        /// </summary>
        public static string EditRepositoryText {
            get {
                return ResourceManager.GetString("EditRepositoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Description.
        /// </summary>
        public static string ErrorDescriptionHeader {
            get {
                return ResourceManager.GetString("ErrorDescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message shown to user.
        /// </summary>
        public static string ErrorMessageHeader {
            get {
                return ResourceManager.GetString("ErrorMessageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension.
        /// </summary>
        public static string ExtensionHeader {
            get {
                return ResourceManager.GetString("ExtensionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string FailedText {
            get {
                return ResourceManager.GetString("FailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileNameHeader {
            get {
                return ResourceManager.GetString("FileNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Deletion Alert.
        /// </summary>
        public static string FilesDeletionAlert {
            get {
                return ResourceManager.GetString("FilesDeletionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FilesDeletionAlert.
        /// </summary>
        public static string FilesDeletionAlertListViewName {
            get {
                return ResourceManager.GetString("FilesDeletionAlertListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Type.
        /// </summary>
        public static string FileTypeHeader {
            get {
                return ResourceManager.GetString("FileTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Identifier URL.
        /// </summary>
        public static string GetIdentifierURLHeader {
            get {
                return ResourceManager.GetString("GetIdentifierURLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Name.
        /// </summary>
        public static string HeaderNameHeader {
            get {
                return ResourceManager.GetString("HeaderNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Names.
        /// </summary>
        public static string HeaderNamesLabel {
            get {
                return ResourceManager.GetString("HeaderNamesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Onboarding tool helps you to create Metadata,
        ///perform a Best Practices Check, and
        ///Post your Data Files to Repository..
        /// </summary>
        public static string HomePageAboutDataOnBoarding1 {
            get {
                return ResourceManager.GetString("HomePageAboutDataOnBoarding1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Onboarding tool helps you to post your tabular data to different repository.
        /// </summary>
        public static string HomePageAboutDataOnBoarding2 {
            get {
                return ResourceManager.GetString("HomePageAboutDataOnBoarding2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiving.
        /// </summary>
        public static string HomePageArchiving {
            get {
                return ResourceManager.GetString("HomePageArchiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documenting.
        /// </summary>
        public static string HomePageDocumenting {
            get {
                return ResourceManager.GetString("HomePageDocumenting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string HomePageFacebook {
            get {
                return ResourceManager.GetString("HomePageFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string HomePageGoogle {
            get {
                return ResourceManager.GetString("HomePageGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live ID.
        /// </summary>
        public static string HomePageLiveID {
            get {
                return ResourceManager.GetString("HomePageLiveID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login With.
        /// </summary>
        public static string HomePageLoginWith {
            get {
                return ResourceManager.GetString("HomePageLoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sharing.
        /// </summary>
        public static string HomePageSharing {
            get {
                return ResourceManager.GetString("HomePageSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View  Demo.
        /// </summary>
        public static string HomePageViewDemo {
            get {
                return ResourceManager.GetString("HomePageViewDemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Data Onboarding.
        /// </summary>
        public static string HomePageWelcomeMsg {
            get {
                return ResourceManager.GetString("HomePageWelcomeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        public static string IdentifierHeader {
            get {
                return ResourceManager.GetString("IdentifierHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifeline Status.
        /// </summary>
        public static string LifelineStatusHeader {
            get {
                return ResourceManager.GetString("LifelineStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Files.
        /// </summary>
        public static string ManageFiles {
            get {
                return ResourceManager.GetString("ManageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Quality Check Rules.
        /// </summary>
        public static string ManageQCRuLesHeader {
            get {
                return ResourceManager.GetString("ManageQCRuLesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Checks.
        /// </summary>
        public static string ManageQualityCheckRules {
            get {
                return ResourceManager.GetString("ManageQualityCheckRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string ManageRepository {
            get {
                return ResourceManager.GetString("ManageRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory.
        /// </summary>
        public static string MandatoryHeader {
            get {
                return ResourceManager.GetString("MandatoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 300 characters..
        /// </summary>
        public static string Max300CharNotification {
            get {
                return ResourceManager.GetString("Max300CharNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MetaData and column desc is loaded from file, please &apos;Save&apos; the data.
        /// </summary>
        public static string MetaDataLoadedFromFile {
            get {
                return ResourceManager.GetString("MetaDataLoadedFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        public static string MetedataTitle {
            get {
                return ResourceManager.GetString("MetedataTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors found..
        /// </summary>
        public static string NoErrorsFound {
            get {
                return ResourceManager.GetString("NoErrorsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no errors in this file..
        /// </summary>
        public static string NoErrorsInThisFileMessage {
            get {
                return ResourceManager.GetString("NoErrorsInThisFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No metadata associated with this repository..
        /// </summary>
        public static string NoMetaDataFound {
            get {
                return ResourceManager.GetString("NoMetaDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no data files published.
        /// </summary>
        public static string NoPublishedFilesInfo {
            get {
                return ResourceManager.GetString("NoPublishedFilesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently no repository supports this file type..
        /// </summary>
        public static string NoRepositoryMessage {
            get {
                return ResourceManager.GetString("NoRepositoryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results..
        /// </summary>
        public static string NoResultsText {
            get {
                return ResourceManager.GetString("NoResultsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no data files uploaded.
        /// </summary>
        public static string NoUploadedFilesInfo {
            get {
                return ResourceManager.GetString("NoUploadedFilesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ordered.
        /// </summary>
        public static string OrderedHeader {
            get {
                return ResourceManager.GetString("OrderedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string PassedText {
            get {
                return ResourceManager.GetString("PassedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post File URL.
        /// </summary>
        public static string PostFileURLHeader {
            get {
                return ResourceManager.GetString("PostFileURLHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        public static string PostTitle {
            get {
                return ResourceManager.GetString("PostTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potential Problem.
        /// </summary>
        public static string PotentialProblem {
            get {
                return ResourceManager.GetString("PotentialProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Date.
        /// </summary>
        public static string PublishedDateHeader {
            get {
                return ResourceManager.GetString("PublishedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PublishedFileList.
        /// </summary>
        public static string PublishedFileListViewName {
            get {
                return ResourceManager.GetString("PublishedFileListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published Data Files.
        /// </summary>
        public static string PublishedFiles {
            get {
                return ResourceManager.GetString("PublishedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Check.
        /// </summary>
        public static string QualityCheckTitle {
            get {
                return ResourceManager.GetString("QualityCheckTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range End.
        /// </summary>
        public static string RangeEndHeader {
            get {
                return ResourceManager.GetString("RangeEndHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range Start.
        /// </summary>
        public static string RangeStartHeader {
            get {
                return ResourceManager.GetString("RangeStartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Selected.
        /// </summary>
        public static string RemoveSelected {
            get {
                return ResourceManager.GetString("RemoveSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Repository.
        /// </summary>
        public static string RepositoryChangeTitle {
            get {
                return ResourceManager.GetString("RepositoryChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string RepositoryHeader {
            get {
                return ResourceManager.GetString("RepositoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Name.
        /// </summary>
        public static string RepositoryNameHeader {
            get {
                return ResourceManager.GetString("RepositoryNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Type.
        /// </summary>
        public static string RepositoryTypeheader {
            get {
                return ResourceManager.GetString("RepositoryTypeheader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Name.
        /// </summary>
        public static string RuleNameLabel {
            get {
                return ResourceManager.GetString("RuleNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string SavedText {
            get {
                return ResourceManager.GetString("SavedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Sheets.
        /// </summary>
        public static string SelectSheetHeader {
            get {
                return ResourceManager.GetString("SelectSheetHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheet Name.
        /// </summary>
        public static string SheetNameHeader {
            get {
                return ResourceManager.GetString("SheetNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string SizeHeader {
            get {
                return ResourceManager.GetString("SizeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusHeader {
            get {
                return ResourceManager.GetString("StatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggested Remedy.
        /// </summary>
        public static string SuggestedRemedy {
            get {
                return ResourceManager.GetString("SuggestedRemedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read the Terms and Conditions.
        /// </summary>
        public static string TermsAndConditionsText {
            get {
                return ResourceManager.GetString("TermsAndConditionsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome | DataUp.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeHeader {
            get {
                return ResourceManager.GetString("TypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Uploaded.
        /// </summary>
        public static string UploadedDateHeader {
            get {
                return ResourceManager.GetString("UploadedDateHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadedFileList.
        /// </summary>
        public static string UploadedFileListViewName {
            get {
                return ResourceManager.GetString("UploadedFileListViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded Data Files.
        /// </summary>
        public static string UploadedFiles {
            get {
                return ResourceManager.GetString("UploadedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string UploadTitle {
            get {
                return ResourceManager.GetString("UploadTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string UpText {
            get {
                return ResourceManager.GetString("UpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agreement.
        /// </summary>
        public static string UserAgreementHeader {
            get {
                return ResourceManager.GetString("UserAgreementHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Admin Users List.
        /// </summary>
        public static string ViewAdminUsersList {
            get {
                return ResourceManager.GetString("ViewAdminUsersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Usage Reports.
        /// </summary>
        public static string ViewUsageReports {
            get {
                return ResourceManager.GetString("ViewUsageReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string VisibilityHeader {
            get {
                return ResourceManager.GetString("VisibilityHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&quot;../Content/images/visible-admin-icon.png&quot; alt=&quot;Admin Only&quot;/&gt;.
        /// </summary>
        public static string VisibleToAdmin {
            get {
                return ResourceManager.GetString("VisibleToAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;img src=&quot;../Content/images/visible-all-icon.png&quot; alt=&quot;Everyone&quot;/&gt;.
        /// </summary>
        public static string VisibleToAll {
            get {
                return ResourceManager.GetString("VisibleToAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why this may be a problem.
        /// </summary>
        public static string WhyThisMayBeAProblem {
            get {
                return ResourceManager.GetString("WhyThisMayBeAProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
