//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DataOnboarding.WebApplication.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DataOnboarding.WebApplication.Resource.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed for the repository..
        /// </summary>
        public static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File contains corrupted data.
        /// </summary>
        public static string CurruptFileErrMsg {
            get {
                return ResourceManager.GetString("CurruptFileErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadFile.
        /// </summary>
        public static string DownloadAction {
            get {
                return ResourceManager.GetString("DownloadAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading uploaded file, retry..
        /// </summary>
        public static string DownLoadErrorMsg {
            get {
                return ResourceManager.GetString("DownLoadErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while downloading from repository, retry..
        /// </summary>
        public static string DownLoadFrmRepErrMsg {
            get {
                return ResourceManager.GetString("DownLoadFrmRepErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownloadFileFromRepository.
        /// </summary>
        public static string DownLoadRepAction {
            get {
                return ResourceManager.GetString("DownLoadRepAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate header names are not allowed..
        /// </summary>
        public static string DuplicateHeaderMsg {
            get {
                return ResourceManager.GetString("DuplicateHeaderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository name exists already, try with other name..
        /// </summary>
        public static string DuplicateRepositoryMsg {
            get {
                return ResourceManager.GetString("DuplicateRepositoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule name exists already, try with other rule name..
        /// </summary>
        public static string DuplicateRuleMsg {
            get {
                return ResourceManager.GetString("DuplicateRuleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid range values..
        /// </summary>
        public static string ErrInvalidRange {
            get {
                return ResourceManager.GetString("ErrInvalidRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sheet is selected..
        /// </summary>
        public static string ErrNoSheetSelected {
            get {
                return ResourceManager.GetString("ErrNoSheetSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range end should be greater than range start..
        /// </summary>
        public static string ErrRangeEndSmall {
            get {
                return ResourceManager.GetString("ErrRangeEndSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while validating the sheet(s).
        /// </summary>
        public static string ErrValidateSheets {
            get {
                return ResourceManager.GetString("ErrValidateSheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the file extensions &apos;;&apos; seperated, like xlsx;csv;....
        /// </summary>
        public static string FileTypeHint {
            get {
                return ResourceManager.GetString("FileTypeHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not support quality check rule validations..
        /// </summary>
        public static string FileTypeNotSupportQCMsg {
            get {
                return ResourceManager.GetString("FileTypeNotSupportQCMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get identifier URL is required..
        /// </summary>
        public static string IdentifierURLRequiredMsg {
            get {
                return ResourceManager.GetString("IdentifierURLRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL format..
        /// </summary>
        public static string InvalidURLMsg {
            get {
                return ResourceManager.GetString("InvalidURLMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header names are missing..
        /// </summary>
        public static string MissHeaderMsg {
            get {
                return ResourceManager.GetString("MissHeaderMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No metadata associated with this repository..
        /// </summary>
        public static string NoMetadataFould {
            get {
                return ResourceManager.GetString("NoMetadataFould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No quality check Rules are defined..
        /// </summary>
        public static string NoQCRulesDefined {
            get {
                return ResourceManager.GetString("NoQCRulesDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No quality check rules exists to validate..
        /// </summary>
        public static string NoQualityCheckRulesFound {
            get {
                return ResourceManager.GetString("NoQualityCheckRulesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories are not available..
        /// </summary>
        public static string NoRepositoriesMsg {
            get {
                return ResourceManager.GetString("NoRepositoriesMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while posting..
        /// </summary>
        public static string PostErrorMessage {
            get {
                return ResourceManager.GetString("PostErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File posted successfully..
        /// </summary>
        public static string PostSuccessMessage {
            get {
                return ResourceManager.GetString("PostSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post file URL is required..
        /// </summary>
        public static string PostURLRequiredMsg {
            get {
                return ResourceManager.GetString("PostURLRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password required..
        /// </summary>
        public static string PwdRequiredMsg {
            get {
                return ResourceManager.GetString("PwdRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality check rule name required..
        /// </summary>
        public static string QCRuleNameRequiredMsg {
            get {
                return ResourceManager.GetString("QCRuleNameRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving quality check rule data. Retry..
        /// </summary>
        public static string QualityCheckErrorMsg {
            get {
                return ResourceManager.GetString("QualityCheckErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository name required..
        /// </summary>
        public static string RepNameRequiredMsg {
            get {
                return ResourceManager.GetString("RepNameRequiredMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while deleting repository. Retry..
        /// </summary>
        public static string RepositoryDelErrMsg {
            get {
                return ResourceManager.GetString("RepositoryDelErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving repository data. Retry..
        /// </summary>
        public static string RepositoryErrMsg {
            get {
                return ResourceManager.GetString("RepositoryErrMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading the file. Retry..
        /// </summary>
        public static string UploadErrorMessage {
            get {
                return ResourceManager.GetString("UploadErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name required..
        /// </summary>
        public static string UserNameRequiredMsg {
            get {
                return ResourceManager.GetString("UserNameRequiredMsg", resourceCulture);
            }
        }
    }
}
