//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DataOnboarding.Utilities.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContentTypes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContentTypes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DataOnboarding.Utilities.Resource.ContentTypes", typeof(ContentTypes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        internal static string _class {
            get {
                return ResourceManager.GetString("class", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/internet-property-stream.
        /// </summary>
        internal static string acx {
            get {
                return ResourceManager.GetString("acx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/postscript.
        /// </summary>
        internal static string ai {
            get {
                return ResourceManager.GetString("ai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-aiff.
        /// </summary>
        internal static string aif {
            get {
                return ResourceManager.GetString("aif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-aiff.
        /// </summary>
        internal static string aifc {
            get {
                return ResourceManager.GetString("aifc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-aiff.
        /// </summary>
        internal static string aiff {
            get {
                return ResourceManager.GetString("aiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-ms-asf.
        /// </summary>
        internal static string asf {
            get {
                return ResourceManager.GetString("asf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-ms-asf.
        /// </summary>
        internal static string asr {
            get {
                return ResourceManager.GetString("asr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-ms-asf.
        /// </summary>
        internal static string asx {
            get {
                return ResourceManager.GetString("asx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/basic.
        /// </summary>
        internal static string au {
            get {
                return ResourceManager.GetString("au", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-msvideo.
        /// </summary>
        internal static string avi {
            get {
                return ResourceManager.GetString("avi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/olescript.
        /// </summary>
        internal static string axs {
            get {
                return ResourceManager.GetString("axs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        internal static string bas {
            get {
                return ResourceManager.GetString("bas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-bcpio.
        /// </summary>
        internal static string bcpio {
            get {
                return ResourceManager.GetString("bcpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        internal static string bin {
            get {
                return ResourceManager.GetString("bin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/bmp.
        /// </summary>
        internal static string bmp {
            get {
                return ResourceManager.GetString("bmp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        internal static string c {
            get {
                return ResourceManager.GetString("c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-pkiseccat.
        /// </summary>
        internal static string cat {
            get {
                return ResourceManager.GetString("cat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-cdf.
        /// </summary>
        internal static string cdf {
            get {
                return ResourceManager.GetString("cdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-netcdf.
        /// </summary>
        internal static string cdf1 {
            get {
                return ResourceManager.GetString("cdf1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-x509-ca-cert.
        /// </summary>
        internal static string cer {
            get {
                return ResourceManager.GetString("cer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msclip.
        /// </summary>
        internal static string clp {
            get {
                return ResourceManager.GetString("clp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-cmx.
        /// </summary>
        internal static string cmx {
            get {
                return ResourceManager.GetString("cmx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/cis-cod.
        /// </summary>
        internal static string cod {
            get {
                return ResourceManager.GetString("cod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-cpio.
        /// </summary>
        internal static string cpio {
            get {
                return ResourceManager.GetString("cpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-mscardfile.
        /// </summary>
        internal static string crd {
            get {
                return ResourceManager.GetString("crd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pkix-crl.
        /// </summary>
        internal static string crl {
            get {
                return ResourceManager.GetString("crl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-x509-ca-cert.
        /// </summary>
        internal static string crt {
            get {
                return ResourceManager.GetString("crt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-csh.
        /// </summary>
        internal static string csh {
            get {
                return ResourceManager.GetString("csh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/css.
        /// </summary>
        internal static string css {
            get {
                return ResourceManager.GetString("css", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/csv.
        /// </summary>
        internal static string csv {
            get {
                return ResourceManager.GetString("csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-director.
        /// </summary>
        internal static string dcr {
            get {
                return ResourceManager.GetString("dcr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-x509-ca-cert.
        /// </summary>
        internal static string der {
            get {
                return ResourceManager.GetString("der", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-director.
        /// </summary>
        internal static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msdownload.
        /// </summary>
        internal static string dll {
            get {
                return ResourceManager.GetString("dll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        internal static string dms {
            get {
                return ResourceManager.GetString("dms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/msword.
        /// </summary>
        internal static string doc {
            get {
                return ResourceManager.GetString("doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.wordprocessingml.document.
        /// </summary>
        internal static string docx {
            get {
                return ResourceManager.GetString("docx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/msword.
        /// </summary>
        internal static string dot {
            get {
                return ResourceManager.GetString("dot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.wordprocessingml.template.
        /// </summary>
        internal static string dotx {
            get {
                return ResourceManager.GetString("dotx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-dvi.
        /// </summary>
        internal static string dvi {
            get {
                return ResourceManager.GetString("dvi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-director.
        /// </summary>
        internal static string dxr {
            get {
                return ResourceManager.GetString("dxr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/postscript.
        /// </summary>
        internal static string eps {
            get {
                return ResourceManager.GetString("eps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/x-setext.
        /// </summary>
        internal static string etx {
            get {
                return ResourceManager.GetString("etx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/envoy.
        /// </summary>
        internal static string evy {
            get {
                return ResourceManager.GetString("evy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        internal static string exe {
            get {
                return ResourceManager.GetString("exe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/fractals.
        /// </summary>
        internal static string fif {
            get {
                return ResourceManager.GetString("fif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-world/x-vrml.
        /// </summary>
        internal static string flr {
            get {
                return ResourceManager.GetString("flr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/gif.
        /// </summary>
        internal static string gif {
            get {
                return ResourceManager.GetString("gif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-gtar.
        /// </summary>
        internal static string gtar {
            get {
                return ResourceManager.GetString("gtar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-gzip.
        /// </summary>
        internal static string gz {
            get {
                return ResourceManager.GetString("gz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        internal static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-hdf.
        /// </summary>
        internal static string hdf {
            get {
                return ResourceManager.GetString("hdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/winhlp.
        /// </summary>
        internal static string hlp {
            get {
                return ResourceManager.GetString("hlp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/mac-binhex40.
        /// </summary>
        internal static string hqx {
            get {
                return ResourceManager.GetString("hqx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/hta.
        /// </summary>
        internal static string hta {
            get {
                return ResourceManager.GetString("hta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/x-component.
        /// </summary>
        internal static string htc {
            get {
                return ResourceManager.GetString("htc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        internal static string htm {
            get {
                return ResourceManager.GetString("htm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        internal static string html {
            get {
                return ResourceManager.GetString("html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/webviewhtml.
        /// </summary>
        internal static string htt {
            get {
                return ResourceManager.GetString("htt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-icon.
        /// </summary>
        internal static string ico {
            get {
                return ResourceManager.GetString("ico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/ief.
        /// </summary>
        internal static string ief {
            get {
                return ResourceManager.GetString("ief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-iphone.
        /// </summary>
        internal static string iii {
            get {
                return ResourceManager.GetString("iii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-internet-signup.
        /// </summary>
        internal static string ins {
            get {
                return ResourceManager.GetString("ins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-internet-signup.
        /// </summary>
        internal static string isp {
            get {
                return ResourceManager.GetString("isp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/pipeg.
        /// </summary>
        internal static string jfif {
            get {
                return ResourceManager.GetString("jfif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg.
        /// </summary>
        internal static string jpe {
            get {
                return ResourceManager.GetString("jpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg.
        /// </summary>
        internal static string jpeg {
            get {
                return ResourceManager.GetString("jpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/jpeg.
        /// </summary>
        internal static string jpg {
            get {
                return ResourceManager.GetString("jpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-javascript.
        /// </summary>
        internal static string js {
            get {
                return ResourceManager.GetString("js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-latex.
        /// </summary>
        internal static string latex {
            get {
                return ResourceManager.GetString("latex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        internal static string lha {
            get {
                return ResourceManager.GetString("lha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-la-asf.
        /// </summary>
        internal static string lsf {
            get {
                return ResourceManager.GetString("lsf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-la-asf.
        /// </summary>
        internal static string lsx {
            get {
                return ResourceManager.GetString("lsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        internal static string lzh {
            get {
                return ResourceManager.GetString("lzh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msmediaview.
        /// </summary>
        internal static string m13 {
            get {
                return ResourceManager.GetString("m13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msmediaview.
        /// </summary>
        internal static string m14 {
            get {
                return ResourceManager.GetString("m14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-mpegurl.
        /// </summary>
        internal static string m3u {
            get {
                return ResourceManager.GetString("m3u", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff-man.
        /// </summary>
        internal static string man {
            get {
                return ResourceManager.GetString("man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msaccess.
        /// </summary>
        internal static string mdb {
            get {
                return ResourceManager.GetString("mdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff-me.
        /// </summary>
        internal static string me {
            get {
                return ResourceManager.GetString("me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message/rfc822.
        /// </summary>
        internal static string mht {
            get {
                return ResourceManager.GetString("mht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message/rfc822.
        /// </summary>
        internal static string mhtml {
            get {
                return ResourceManager.GetString("mhtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/mid.
        /// </summary>
        internal static string mid {
            get {
                return ResourceManager.GetString("mid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msmoney.
        /// </summary>
        internal static string mny {
            get {
                return ResourceManager.GetString("mny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/quicktime.
        /// </summary>
        internal static string mov {
            get {
                return ResourceManager.GetString("mov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/x-sgi-movie.
        /// </summary>
        internal static string movie {
            get {
                return ResourceManager.GetString("movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        internal static string mp2 {
            get {
                return ResourceManager.GetString("mp2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/mpeg.
        /// </summary>
        internal static string mp3 {
            get {
                return ResourceManager.GetString("mp3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        internal static string mpa {
            get {
                return ResourceManager.GetString("mpa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        internal static string mpe {
            get {
                return ResourceManager.GetString("mpe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        internal static string mpeg {
            get {
                return ResourceManager.GetString("mpeg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        internal static string mpg {
            get {
                return ResourceManager.GetString("mpg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-project.
        /// </summary>
        internal static string mpp {
            get {
                return ResourceManager.GetString("mpp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/mpeg.
        /// </summary>
        internal static string mpv2 {
            get {
                return ResourceManager.GetString("mpv2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff-ms.
        /// </summary>
        internal static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-outlook.
        /// </summary>
        internal static string msg {
            get {
                return ResourceManager.GetString("msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msmediaview.
        /// </summary>
        internal static string mvb {
            get {
                return ResourceManager.GetString("mvb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-netcdf.
        /// </summary>
        internal static string nc {
            get {
                return ResourceManager.GetString("nc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to message/rfc822.
        /// </summary>
        internal static string nws {
            get {
                return ResourceManager.GetString("nws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/oda.
        /// </summary>
        internal static string oda {
            get {
                return ResourceManager.GetString("oda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pkcs10.
        /// </summary>
        internal static string p10 {
            get {
                return ResourceManager.GetString("p10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs12.
        /// </summary>
        internal static string p12 {
            get {
                return ResourceManager.GetString("p12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-certificates.
        /// </summary>
        internal static string p7b {
            get {
                return ResourceManager.GetString("p7b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-mime.
        /// </summary>
        internal static string p7c {
            get {
                return ResourceManager.GetString("p7c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-mime.
        /// </summary>
        internal static string p7m {
            get {
                return ResourceManager.GetString("p7m", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-certreqresp.
        /// </summary>
        internal static string p7r {
            get {
                return ResourceManager.GetString("p7r", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-signature.
        /// </summary>
        internal static string p7s {
            get {
                return ResourceManager.GetString("p7s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-portable-bitmap.
        /// </summary>
        internal static string pbm {
            get {
                return ResourceManager.GetString("pbm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pdf.
        /// </summary>
        internal static string pdf {
            get {
                return ResourceManager.GetString("pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs12.
        /// </summary>
        internal static string pfx {
            get {
                return ResourceManager.GetString("pfx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-portable-graymap.
        /// </summary>
        internal static string pgm {
            get {
                return ResourceManager.GetString("pgm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/ynd.ms-pkipko.
        /// </summary>
        internal static string pko {
            get {
                return ResourceManager.GetString("pko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-perfmon.
        /// </summary>
        internal static string pma {
            get {
                return ResourceManager.GetString("pma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-perfmon.
        /// </summary>
        internal static string pmc {
            get {
                return ResourceManager.GetString("pmc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-perfmon.
        /// </summary>
        internal static string pml {
            get {
                return ResourceManager.GetString("pml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-perfmon.
        /// </summary>
        internal static string pmr {
            get {
                return ResourceManager.GetString("pmr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-perfmon.
        /// </summary>
        internal static string pmw {
            get {
                return ResourceManager.GetString("pmw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/png.
        /// </summary>
        internal static string png {
            get {
                return ResourceManager.GetString("png", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-portable-anymap.
        /// </summary>
        internal static string pnm {
            get {
                return ResourceManager.GetString("pnm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.
        /// </summary>
        internal static string pot {
            get {
                return ResourceManager.GetString("pot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.presentationml.template.
        /// </summary>
        internal static string potx {
            get {
                return ResourceManager.GetString("potx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-portable-pixmap.
        /// </summary>
        internal static string ppm {
            get {
                return ResourceManager.GetString("ppm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.
        /// </summary>
        internal static string pps {
            get {
                return ResourceManager.GetString("pps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.presentationml.slideshow.
        /// </summary>
        internal static string ppsx {
            get {
                return ResourceManager.GetString("ppsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-powerpoint.
        /// </summary>
        internal static string ppt {
            get {
                return ResourceManager.GetString("ppt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.presentationml.presentation.
        /// </summary>
        internal static string pptx {
            get {
                return ResourceManager.GetString("pptx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/pics-rules.
        /// </summary>
        internal static string prf {
            get {
                return ResourceManager.GetString("prf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/postscript.
        /// </summary>
        internal static string ps {
            get {
                return ResourceManager.GetString("ps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-mspublisher.
        /// </summary>
        internal static string pub {
            get {
                return ResourceManager.GetString("pub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to video/quicktime.
        /// </summary>
        internal static string qt {
            get {
                return ResourceManager.GetString("qt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-pn-realaudio.
        /// </summary>
        internal static string ra {
            get {
                return ResourceManager.GetString("ra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-pn-realaudio.
        /// </summary>
        internal static string ram {
            get {
                return ResourceManager.GetString("ram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-cmu-raster.
        /// </summary>
        internal static string ras {
            get {
                return ResourceManager.GetString("ras", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-rgb.
        /// </summary>
        internal static string rgb {
            get {
                return ResourceManager.GetString("rgb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/mid.
        /// </summary>
        internal static string rmi {
            get {
                return ResourceManager.GetString("rmi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff.
        /// </summary>
        internal static string roff {
            get {
                return ResourceManager.GetString("roff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/rtf.
        /// </summary>
        internal static string rtf {
            get {
                return ResourceManager.GetString("rtf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/richtext.
        /// </summary>
        internal static string rtx {
            get {
                return ResourceManager.GetString("rtx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msschedule.
        /// </summary>
        internal static string scd {
            get {
                return ResourceManager.GetString("scd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/scriptlet.
        /// </summary>
        internal static string sct {
            get {
                return ResourceManager.GetString("sct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/set-payment-initiation.
        /// </summary>
        internal static string setpay {
            get {
                return ResourceManager.GetString("setpay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/set-registration-initiation.
        /// </summary>
        internal static string setreg {
            get {
                return ResourceManager.GetString("setreg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-sh.
        /// </summary>
        internal static string sh {
            get {
                return ResourceManager.GetString("sh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-shar.
        /// </summary>
        internal static string shar {
            get {
                return ResourceManager.GetString("shar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-stuffit.
        /// </summary>
        internal static string sit {
            get {
                return ResourceManager.GetString("sit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/basic.
        /// </summary>
        internal static string snd {
            get {
                return ResourceManager.GetString("snd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-pkcs7-certificates.
        /// </summary>
        internal static string spc {
            get {
                return ResourceManager.GetString("spc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/futuresplash.
        /// </summary>
        internal static string spl {
            get {
                return ResourceManager.GetString("spl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-wais-source.
        /// </summary>
        internal static string src {
            get {
                return ResourceManager.GetString("src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-pkicertstore.
        /// </summary>
        internal static string sst {
            get {
                return ResourceManager.GetString("sst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-pkistl.
        /// </summary>
        internal static string stl {
            get {
                return ResourceManager.GetString("stl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/html.
        /// </summary>
        internal static string stm {
            get {
                return ResourceManager.GetString("stm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-sv4cpio.
        /// </summary>
        internal static string sv4cpio {
            get {
                return ResourceManager.GetString("sv4cpio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-sv4crc.
        /// </summary>
        internal static string sv4crc {
            get {
                return ResourceManager.GetString("sv4crc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/svg+xml.
        /// </summary>
        internal static string svg {
            get {
                return ResourceManager.GetString("svg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-shockwave-flash.
        /// </summary>
        internal static string swf {
            get {
                return ResourceManager.GetString("swf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff.
        /// </summary>
        internal static string t {
            get {
                return ResourceManager.GetString("t", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-tar.
        /// </summary>
        internal static string tar {
            get {
                return ResourceManager.GetString("tar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-tcl.
        /// </summary>
        internal static string tcl {
            get {
                return ResourceManager.GetString("tcl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-tex.
        /// </summary>
        internal static string tex {
            get {
                return ResourceManager.GetString("tex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-texinfo.
        /// </summary>
        internal static string texi {
            get {
                return ResourceManager.GetString("texi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-texinfo.
        /// </summary>
        internal static string texinfo {
            get {
                return ResourceManager.GetString("texinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-compressed.
        /// </summary>
        internal static string tgz {
            get {
                return ResourceManager.GetString("tgz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/tiff.
        /// </summary>
        internal static string tif {
            get {
                return ResourceManager.GetString("tif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/tiff.
        /// </summary>
        internal static string tiff {
            get {
                return ResourceManager.GetString("tiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-troff.
        /// </summary>
        internal static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msterminal.
        /// </summary>
        internal static string trm {
            get {
                return ResourceManager.GetString("trm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/tab-separated-values.
        /// </summary>
        internal static string tsv {
            get {
                return ResourceManager.GetString("tsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/plain.
        /// </summary>
        internal static string txt {
            get {
                return ResourceManager.GetString("txt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/iuls.
        /// </summary>
        internal static string uls {
            get {
                return ResourceManager.GetString("uls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-ustar.
        /// </summary>
        internal static string ustar {
            get {
                return ResourceManager.GetString("ustar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text/x-vcard.
        /// </summary>
        internal static string vcf {
            get {
                return ResourceManager.GetString("vcf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-world/x-vrml.
        /// </summary>
        internal static string vrml {
            get {
                return ResourceManager.GetString("vrml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to audio/x-wav.
        /// </summary>
        internal static string wav {
            get {
                return ResourceManager.GetString("wav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-works.
        /// </summary>
        internal static string wcm {
            get {
                return ResourceManager.GetString("wcm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-works.
        /// </summary>
        internal static string wdb {
            get {
                return ResourceManager.GetString("wdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-works.
        /// </summary>
        internal static string wks {
            get {
                return ResourceManager.GetString("wks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/octet-stream.
        /// </summary>
        internal static string wkt {
            get {
                return ResourceManager.GetString("wkt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-msmetafile.
        /// </summary>
        internal static string wmf {
            get {
                return ResourceManager.GetString("wmf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  video/x-ms-wmv.
        /// </summary>
        internal static string wmv {
            get {
                return ResourceManager.GetString("wmv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-works.
        /// </summary>
        internal static string wps {
            get {
                return ResourceManager.GetString("wps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-mswrite.
        /// </summary>
        internal static string wri {
            get {
                return ResourceManager.GetString("wri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-world/x-vrml.
        /// </summary>
        internal static string wrl {
            get {
                return ResourceManager.GetString("wrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-world/x-vrml.
        /// </summary>
        internal static string wrz {
            get {
                return ResourceManager.GetString("wrz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-world/x-vrml.
        /// </summary>
        internal static string xaf {
            get {
                return ResourceManager.GetString("xaf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-xbitmap.
        /// </summary>
        internal static string xbm {
            get {
                return ResourceManager.GetString("xbm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        internal static string xla {
            get {
                return ResourceManager.GetString("xla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        internal static string xlc {
            get {
                return ResourceManager.GetString("xlc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        internal static string xlm {
            get {
                return ResourceManager.GetString("xlm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        internal static string xls {
            get {
                return ResourceManager.GetString("xls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.
        /// </summary>
        internal static string xlsx {
            get {
                return ResourceManager.GetString("xlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        internal static string xlt {
            get {
                return ResourceManager.GetString("xlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.openxmlformats-officedocument.spreadsheetml.template.
        /// </summary>
        internal static string xltx {
            get {
                return ResourceManager.GetString("xltx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/vnd.ms-excel.
        /// </summary>
        internal static string xlw {
            get {
                return ResourceManager.GetString("xlw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to x-world/x-vrml.
        /// </summary>
        internal static string xof {
            get {
                return ResourceManager.GetString("xof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-xpixmap.
        /// </summary>
        internal static string xpm {
            get {
                return ResourceManager.GetString("xpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image/x-xwindowdump.
        /// </summary>
        internal static string xwd {
            get {
                return ResourceManager.GetString("xwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/x-compress.
        /// </summary>
        internal static string z {
            get {
                return ResourceManager.GetString("z", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to application/zip.
        /// </summary>
        internal static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
