//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Research.DataOnboarding.WebApi.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MessageStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MessageStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Research.DataOnboarding.WebApi.Resources.MessageStrings", typeof(MessageStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to SkyDrive is not provided.
        /// </summary>
        public static string Access_Token_Is_Null {
            get {
                return ResourceManager.GetString("Access_Token_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null, empty or whitespace values are not valid for &apos;{0}&apos;..
        /// </summary>
        public static string Argument_Error_Message_Template {
            get {
                return ResourceManager.GetString("Argument_Error_Message_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citation is not supported for {0} repositories..
        /// </summary>
        public static string CitationNotSupportedMessage {
            get {
                return ResourceManager.GetString("CitationNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column level metadata is available only for xlsx and csv files..
        /// </summary>
        public static string ColumnLevelMetadataNotSupportedErrorMessage {
            get {
                return ResourceManager.GetString("ColumnLevelMetadataNotSupportedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact data onboarding support..
        /// </summary>
        public static string Contact_Support {
            get {
                return ResourceManager.GetString("Contact_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download URL is empty.
        /// </summary>
        public static string Download_URL_Empty {
            get {
                return ResourceManager.GetString("Download_URL_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File already published.
        /// </summary>
        public static string File_Already_Published {
            get {
                return ResourceManager.GetString("File_Already_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not associated with any repository.
        /// </summary>
        public static string File_Repository_Is_Null {
            get {
                return ResourceManager.GetString("File_Repository_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Service outage. Contact Data Onboarding support..
        /// </summary>
        public static string File_Service_Is_Null {
            get {
                return ResourceManager.GetString("File_Service_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File deleted or does not exist in repository.
        /// </summary>
        public static string FileDoesNotExistInRepository {
            get {
                return ResourceManager.GetString("FileDoesNotExistInRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File doesn&apos;t exist..
        /// </summary>
        public static string FileDoesntExist {
            get {
                return ResourceManager.GetString("FileDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download input data is empty.
        /// </summary>
        public static string Input_Data_Unavailable {
            get {
                return ResourceManager.GetString("Input_Data_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        public static string Invalid_File_Id {
            get {
                return ResourceManager.GetString("Invalid_File_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid repository id..
        /// </summary>
        public static string Invalid_Repository_id {
            get {
                return ResourceManager.GetString("Invalid_Repository_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data is not valid. .
        /// </summary>
        public static string Invalid_User_Data {
            get {
                return ResourceManager.GetString("Invalid_User_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid error types..
        /// </summary>
        public static string InvalidErrorTypes {
            get {
                return ResourceManager.GetString("InvalidErrorTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid repository name..
        /// </summary>
        public static string InvalidRepositoryName {
            get {
                return ResourceManager.GetString("InvalidRepositoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Metadata value for the field {0}..
        /// </summary>
        public static string Metadata_Field_Value_Type_Mismatch_Template {
            get {
                return ResourceManager.GetString("Metadata_Field_Value_Type_Mismatch_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Metadata Type for the field {0}.
        /// </summary>
        public static string Metadata_Type_Not_Found_Template {
            get {
                return ResourceManager.GetString("Metadata_Type_Not_Found_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-empty file name is needed.
        /// </summary>
        public static string NoFileNameError {
            get {
                return ResourceManager.GetString("NoFileNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No metadata associated with this repository..
        /// </summary>
        public static string NoMetadataFould {
            get {
                return ResourceManager.GetString("NoMetadataFould", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QC service is outage. Contact Data Onboarding support..
        /// </summary>
        public static string QC_Service_Is_Null {
            get {
                return ResourceManager.GetString("QC_Service_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality check is available only for xlsx and csv files..
        /// </summary>
        public static string QualityCheckNotSupportedErrorMessage {
            get {
                return ResourceManager.GetString("QualityCheckNotSupportedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline Access to SkyDrive must be provided.
        /// </summary>
        public static string Refresh_Token_Is_Null {
            get {
                return ResourceManager.GetString("Refresh_Token_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Not Found.
        /// </summary>
        public static string Repository_Not_Found {
            get {
                return ResourceManager.GetString("Repository_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository service outage. Contact Data Onboarding support..
        /// </summary>
        public static string Repository_Service_Is_Null {
            get {
                return ResourceManager.GetString("Repository_Service_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Field Metadata is not provided for the field {0}.
        /// </summary>
        public static string Required_Field_Metadata_Not_Found_Template {
            get {
                return ResourceManager.GetString("Required_Field_Metadata_Not_Found_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service cannot post file to a repository that is not impersonated..
        /// </summary>
        public static string ServiceCannotPostFileToARepositoryThatIsNotImpersonated {
            get {
                return ResourceManager.GetString("ServiceCannotPostFileToARepositoryThatIsNotImpersonated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datetime value for Token Expiry does not exist.
        /// </summary>
        public static string Token_Expires_Is_Null {
            get {
                return ResourceManager.GetString("Token_Expires_Is_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not overwrite the file as a file with same name {0}  is already in the process of publishing..
        /// </summary>
        public static string Upload_Validation_Error_Template {
            get {
                return ResourceManager.GetString("Upload_Validation_Error_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UploadFailed.
        /// </summary>
        public static string UploadFailed {
            get {
                return ResourceManager.GetString("UploadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists..
        /// </summary>
        public static string User_Already_Exists {
            get {
                return ResourceManager.GetString("User_Already_Exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data could not be updated. .
        /// </summary>
        public static string User_Data_Update_Error_Message {
            get {
                return ResourceManager.GetString("User_Data_Update_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string User_Not_Found {
            get {
                return ResourceManager.GetString("User_Not_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User service outage. Contact Data Onboarding support..
        /// </summary>
        public static string User_Service_Is_Null {
            get {
                return ResourceManager.GetString("User_Service_Is_Null", resourceCulture);
            }
        }
    }
}
